"""relation fixed

Revision ID: 302b9437ff5c
Revises: c752e08efbde
Create Date: 2023-06-28 23:47:43.117284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302b9437ff5c'
down_revision = 'c752e08efbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('dogs_table_owner_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_table', ['owner_id'], ['id'])
        batch_op.drop_column('owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('dogs_table_owner_fkey', 'users_table', ['owner'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
