"""empty message

Revision ID: 347752e001c4
Revises: 4d6093a6f86f
Create Date: 2023-06-26 13:54:06.535145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347752e001c4'
down_revision = '4d6093a6f86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dogs_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dogs_table_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dogs_table_name'))

    op.drop_table('dogs_table')
    # ### end Alembic commands ###
