"""empty message

Revision ID: c752e08efbde
Revises: 347752e001c4
Create Date: 2023-06-26 22:57:25.398213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c752e08efbde'
down_revision = '347752e001c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_surname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_email', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_password_hash', sa.String(length=150), nullable=True))
        batch_op.drop_index('ix_users_table_email')
        batch_op.drop_index('ix_users_table_username')
        batch_op.create_index(batch_op.f('ix_users_table_user_email'), ['user_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_table_user_name'), ['user_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_table_user_surname'), ['user_surname'], unique=False)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_table_user_surname'))
        batch_op.drop_index(batch_op.f('ix_users_table_user_name'))
        batch_op.drop_index(batch_op.f('ix_users_table_user_email'))
        batch_op.create_index('ix_users_table_username', ['username'], unique=False)
        batch_op.create_index('ix_users_table_email', ['email'], unique=False)
        batch_op.drop_column('user_password_hash')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_surname')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
